# Generated by Django 4.2.6 on 2023-10-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_delete_item_delete_products"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="brand",),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.RemoveField(model_name="product", name="created_at",),
        migrations.RemoveField(model_name="product", name="in_stock",),
        migrations.RemoveField(model_name="product", name="updated_at",),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
